services:
  - type: web
    name: superviva-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -e .
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.10.0"
